### ISSUE TITLE
how to set --read_len READ_LENGTH

### ISSUE THREAD

**Issue by WellJoea** [canzarlab/McSplicer#2]
how to set --read_len READ_LENGTH?

**Comment by WellJoea** [comment]
there is a bug in script "McSplicer.py"

423     if  out_file == '':
424         out_filename = out_DIR + gene_id+'.csv'
425     else:
426         out_filename = out_DIR + gene_id+'_'+out_file +'.csv'

**Comment by israa-alqassem** [comment]
1. If your read length is 100bp you set the read_len argument like:
              --read_len 100
I'd recommend you have a look at the examples in the subfolder ./examples and the python script run_ENOPH1_gene_example.py, as we provide a detailed description of how we run McSplicer.


2. Regarding the bug, could you explain what the bug is? In the if-else statement that you copied, we set the "--prefix" argument, again please have a look at run_ENOPH1_gene_example.py to see how we set this argument.

Regards,
